### ISSUE TITLE
Is this package still actively developed?

### ISSUE THREAD

**Issue by pllim** [rkern/line_profiler#144]
I cannot do `pip install line_profiler` and it seems like last commit was on Dec 2017. Should I look somewhere else for a profiler package?

**Comment by caethan** [comment]
I am aware of the problem and will fix it when I get some time.  I also have a sick six-month-old and a full time job that doesn't support this work, so time is in short supply.  You are welcome to look elsewhere, or to fork and do as you see fit, or to install directly from git (the problem is the compiled Cython uploaded to pypi), if the issue isn't being fixed fast enough for your comfort.

**Comment by pllim** [comment]
Sorry to hear and I hope everyone feels better soon. Thanks for the package as it is very useful and allowed me to profile code inside a notebook. I saw it mentioned in several different blogs and that was how I found it. Your work is appreciated!
