### ISSUE TITLE
kernprof.py -m package

### ISSUE THREAD

**Issue by anntzer** [rkern/line_profiler#3]
Support for running `package.__main__` via `kernprof.py -m package` would be appreciated, thanks.

**Comment by embray** [comment]
I think this would be really useful to have, but of course it's not entirely trivial.  My main question would be how to handle profiling imports within the module.  Should each imported module be profiled as well--or should a module only be profiled if it's also been tagged for profiling (a la LineProfiler.add_function, but for a module)?

**Comment by anntzer** [comment]
My optimal command-line experience would be something like
````
$ kernprof --profile-funcs=qualified.function.name,... --profile-imports=qualified.module.name,... \
    [script.py | -c "commands" | -m module]
```
Then there's no need to edit the file for profiling, you can just save a tiny script for that.

**Comment by rkern** [comment]
I interpret the request as simply enabling `-m package` for locating the entrypoint of the script and properly initializing it, not as actually profiling everything in `package/__main__.py`. One would still use `@profile` or whatever to mark the methods that are to be profiled.

**Comment by embray** [comment]
Ah, I interpreted this maybe as something more like #26, that is, profiling module-level code that is not in a function.  I have some ideas for making that work if you'd be interested in a patch.

**Comment by anntzer** [comment]
(I was also initially talking about @rkern's interpretation -- my next comment is further down on my wishlist.)

**Comment by rkern** [comment]
@Lan1991Xu This issue is unrelated to your problem. Please open a new issue with more information. Please create a complete, minimal example that we can run that demonstrates the problem. Thanks.

**Comment by Lan1991Xu** [comment]
OK，thanks for your reply

**Comment by mattkatz** [comment]
Really like line_profiler - it's helped me immensely.
I also really like anntzer's idea of a --profile-funcs option. I'm profiling repeatedly as I develop when I have to optimize a call. I set up entr to automatically rerun line_profile one every save. 

However, if i also want other windows to run the same code, but not under profile, I have to put in a fake profile decorator that everything else uses.

A very helpful workflow would be to pass the profiling functions on the command line so they can be wrapped then before being run - but leave the pure code alone so that other timing and unit testing scripts can continue to work.
