### ISSUE TITLE
ImportError undefined symbol: PyUnicodeUCS4_DecodeUTF8

### ISSUE THREAD

**Issue by Johnathon332** [rkern/line_profiler#41]
When I try to run the command python -m line_profiler 1e3fdc80f5419f682e65b410f2a2ef92135d3d046_1800.py.lprof

I get the error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/line_profiler.py", line 20, in <module>
    from _line_profiler import LineProfiler as CLineProfiler
ImportError: /usr/local/lib/python2.7/dist-packages/_line_profiler.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8

Is this a problem with my pip or is it a bug?  I am betting that it is more of a problem with pip, however how do I go about fixing this

**Comment by rkern** [comment]
It looks like you are using a `line_profiler` binary built with a version of the `python` interpreter built for UCS4 but running it with a different `python` interpreter built for UCS2.

**Comment by rkern** [comment]
Most standard Linux distro packages for `python` standardize on UCS4. It looks like you are running a local build of `python`? You can change its configuration (keeping in mind that you may need to rebuild all of your extensions) like so:  `./configure --enable-unicode=ucs4`

Or just rebuild `line_profiler` using your `/usr/local/bin/python` instead of `/usr/bin/python`. But doing the extra effort to make your `/usr/local/bin/python` binary compatible with `/usr/bin/python` may make for a more harmonious future for you. :-)
